apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fuseki.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "fuseki.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "fuseki.fullname" . }}-headless
  {{- if not .Values.fuseki.autoscaling.enabled }}
  replicas: {{ .Values.fuseki.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fuseki.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fuseki.labels" . | nindent 8 }}
    spec:
      {{- with .Values.fuseki.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.fuseki.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.fuseki.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fuseki.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.fuseki.podSecurityContext | nindent 8 }}
      containers:
        - name: fuseki
          securityContext:
            {{- toYaml .Values.fuseki.securityContext | nindent 12 }}
          image: "{{ .Values.fuseki.image.repository }}:{{ .Values.fuseki.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.fuseki.image.pullPolicy }}
          ports:
            - name: fusekihttp
              containerPort: {{ .Values.fuseki.service.ports.fusekihttp.containerPort }}
              protocol: {{ .Values.fuseki.service.ports.fusekihttp.protocol }}
          resources:
            {{- toYaml .Values.fuseki.resources | nindent 12 }}
          {{- with .Values.fuseki.envVars }}
          env:
            - name: EXAMPLE_ENV_VAR
              value: {{ .exampleEnvVar | quote }}
          {{- end }}
          volumeMounts:
            {{- if .Values.fuseki.persistence.enabled }}
            - name: data
              mountPath: /run
            {{- end }}
      volumes:
  {{- if and .Values.fuseki.persistence.enabled .Values.fuseki.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.fuseki.persistence.existingClaim $ }}
  {{- else if not .Values.fuseki.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        {{- range .Values.fuseki.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.fuseki.persistence.size | quote }}
  {{- end }}
